# Generated by Django 5.0.6 on 2024-06-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoriya',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriya'},
        ),
        migrations.AlterModelOptions(
            name='mahsulot_rasm',
            options={'verbose_name': 'Mahsulot_rasm', 'verbose_name_plural': 'Mahsulot_rasm'},
        ),
        migrations.AlterModelOptions(
            name='mahsulotlar',
            options={'verbose_name': 'Mahsulotlar', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
